version: "3.1"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - app
    env_file: ./.env
  app:
    image: openjdk:8-jdk-alpine
    container_name: app
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
        - ./build/libs/ussd-ag-banking-0.0.1-SNAPSHOT.jar:/app.jar
    command:
      - java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=5005,suspend=n -jar /app.jar
      - --spring.profiles.active=dev
      - --spring.config.location=file:/config/application.yml
      - --logging.config=file:/config/logback.xml
      - --spring.cloud.config.uri=http://config:8888
      - --spring.cloud.config.label=master
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  oracle:
    image: wnameless/oracle-xe-11g
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
